language: node_js
node_js: 12
before_install:
- npm install -g npm@latest
install:
- npm ci
script:
- make validate-no-uncommitted-package-lock-changes
- npm run i18n_extract
- npm run lint
- npm run test
- npm run build
- npm run npm-build
- npm run is-es5
after_success:
- npm run semantic-release
- codecov
env:
  global:
  # Github Token
  - secure: mGzJWnyq02cYIq2lwSF7sWX5WlC6OJ+8zKy68IXsMvE7nwmKmcUHAPT/HOftAdLr6rMjQsMESc1QySb7YfV0pH5InN4hHLhHENPOydNpLByWxI4FL47/AuZ2jF75qzxrLmgvid+PyK0XTNVyrNre4l4U/MbuufY7sC4hRndeLwkryugjBZowAff3QbjSPd8Tjc07DHkqZgwsrk6qU5quMntEc7qcm2JMWzI/xu/+EW+BUUPs4JBJCNWByDAx84TG11p0BTZao8cKEx0WoBzb/veS8T3ykkvShq3PbPIGuN6MCMqnVwtvwtBfIVnQOnsVsB+gQAK3fl/11bYTfnP5zeZ/c51hfxQ25zbINUWgbkru8GzLMBMsP9jYjaSHl07fqS/zq/VwnXxPSBmooCl5gEsB78EED7qfI9V06WoICAbMdlDolNPGNclPHlDFqSDr1YEJ+RSfn1E7cQXPieQSwNboFbAQO47fm4AjTxcCdFjBXeYG01E2gGXAOnT+zVKy4zN0GPWl4fz/BCu/4S70fCl3xZuv8hDk1XBQIiJuvgn22w3BpwfseJIn73lI+RiJy5WHMJ/H3Ud5dxeaGB4SnfpAaGGO9A60+qG5hR4wOrYDLs1AqTi2iNHMfJZyuv9VLBovX7UaQY7QmHRnuiyVMFNczO2UJlnUftfEgR0UJ6k=
  # NPM Token
  - secure: fGnePXWz1hK6u+/GI0S9a7iXptclji07zwc2qsCcDL/quKztPBt7m5+FUwPpwlLAm0pCXu52BKI9SnkkpN+2r55PMBjdko6XxW5KrR4EtGC2kQ+e3t1UHiTQ73uWGpZm6kGTMDmTNMB8iRsymvL3+N2/1LkzrTqB1OfnOAskinJ4qiIyJ600vUwczS8BuvGBGQaF7oVuqhDVGget3txBdox1ZF1lBmo50ZIzV4UUi1pC40VVARRmTBDOfJ0C+zToIe6oD6kpcLJG4IEjUq8GP6vze17Ik564NbGEU1bkebbEt5HLreuNZsN3M5kPOiMrbv+DtBuEglfUEX7EsQjhrYzk1upTLWIR0fLIIQ9JHpylyltrwjNuev/XjAFZkaiVLmhg7uWH94xRZ8ER5GX2KCezYGpf6a7ibdgw1xpaR5Gs2Ur9SaXPt7rNkpzUO9/CFsb6jq61UXSILuL82hEiaPm1rDAhmFrNHcm6PAGZBnrr8HhBN+8JR1oql+AroO1KFhZvLnhBkL64vqzMnxquOR679Wvep8tC+QjLQv+QjUpz33+u21k1PwEb3WI5zyE0M6y6ppOPdjjP8uwI7mnYQE3hKpjt1m9e037j1vPw/KBFxP6qgjwAsiswpUoBVtuXWEdj5gyYFwiSLB0xGwdLJW2Sylj9A2BDGO1c+2lVnhw=
