---
name: ci
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 12
        npm-test:
        - i18n_extract
        - is-es5
        - lint
        - test
    steps:
    - uses: actions/checkout@v2
    - uses: dcodeIO/setup-node-nvm@master
    - run: make requirements
    - run: make test NPM_TESTS=build
    - run: make test NPM_TESTS=${{ matrix.npm-test }}
    - name: upload coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
